# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  pre-build:
    docker:
      - image: circleci/node:10.16.0-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/notes
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Tests
          command: npm run test -- --no-watch --browsers=FirefoxHeadless --source-map=false
  build-dev:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - run:
          name: Build
          command: npm run build
  build-prod:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - run:
          name: Build Prod
          command: npm run build:prod
  deploy-dev:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting -P default
  deploy-prod:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - run:
          name: Firebase Deploy Prod
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting -P prod
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - pre-build:
          filters:
            branches:
              only:
                - develop
                - master
      - build-dev:
          requires:
            - pre-build
          filters:
            branches:
              only:
                - develop
      - build-prod:
          requires:
            - pre-build
          filters:
            branches:
              only:
                - master
      - deploy-dev:
          requires:
            - build-dev
          filters:
            branches:
              only: develop
      - deploy-prod:
          requires:
            - build-prod
          filters:
            branches:
              only: master
